
INSERT INTO `{$wpdb->prefix}incluyeme_cities` (`incluyeme_cities_id`, `cities_name`, `cities_location`)
VALUES (51, 'Ech-Chleff (el-Asnam)', 'Chlef'),
       (52, 'Gharda', 'Gharda'),
       (53, 'Tafuna', 'Tutuila'),
       (54, 'Fagatogo', 'Tutuila'),
       (55, 'Andorra la Vella', 'Andorra la Vella'),
       (56, 'Luanda', 'Luanda'),
       (57, 'Huambo', 'Huambo'),
       (58, 'Lobito', 'Benguela'),
       (59, 'Benguela', 'Benguela'),
       (60, 'Namibe', 'Namibe'),
       (61, 'South Hill', '?'),
       (62, 'The Valley', '?'),
       (63, 'Saint John?s', 'St John'),
       (64, 'Dubai', 'Dubai'),
       (65, 'Abu Dhabi', 'Abu Dhabi'),
       (66, 'Sharja', 'Sharja'),
       (67, 'al-Ayn', 'Abu Dhabi'),
       (68, 'Ajman', 'Ajman'),
       (69, 'Buenos Aires', 'Distrito Federal'),
       (70, 'La Matanza', 'Buenos Aires'),
       (71, 'C?rdoba', 'C?rdoba'),
       (72, 'Rosario', 'Santa F'),
       (73, 'Lomas de Zamora', 'Buenos Aires'),
       (74, 'Quilmes', 'Buenos Aires'),
       (75, 'Almirante Brown', 'Buenos Aires'),
       (76, 'La Plata', 'Buenos Aires'),
       (77, 'Mar del Plata', 'Buenos Aires'),
       (78, 'San Miguel de Tucum', 'Tucum'),
       (79, 'Lan?s', 'Buenos Aires'),
       (80, 'Merlo', 'Buenos Aires'),
       (81, 'General San Mart', 'Buenos Aires'),
       (82, 'Salta', 'Salta'),
       (83, 'Moreno', 'Buenos Aires'),
       (84, 'Santa F', 'Santa F'),
       (85, 'Avellaneda', 'Buenos Aires'),
       (86, 'Tres de Febrero', 'Buenos Aires'),
       (87, 'Mor', 'Buenos Aires'),
       (88, 'Florencio Varela', 'Buenos Aires'),
       (89, 'San Isidro', 'Buenos Aires'),
       (90, 'Tigre', 'Buenos Aires'),
       (91, 'Malvinas Argentinas', 'Buenos Aires'),
       (92, 'Vicente L?pez', 'Buenos Aires'),
       (93, 'Berazategui', 'Buenos Aires'),
       (94, 'Corrientes', 'Corrientes'),
       (95, 'San Miguel', 'Buenos Aires'),
       (96, 'Bah?a Blanca', 'Buenos Aires'),
       (97, 'Esteban Echeverr', 'Buenos Aires'),
       (98, 'Resistencia', 'Chaco'),
       (99, 'Jos? C. Paz', 'Buenos Aires'),
       (100, 'Paran', 'Entre Rios'),
       (101, 'Godoy Cruz', 'Mendoza'),
       (102, 'Posadas', 'Misiones'),
       (103, 'Guaymall', 'Mendoza'),
       (104, 'Santiago del Estero', 'Santiago del Estero'),
       (105, 'San Salvador de Jujuy', 'Jujuy'),
       (106, 'Hurlingham', 'Buenos Aires'),
       (107, 'Neuqu', 'Neuqu'),
       (108, 'Ituzaing', 'Buenos Aires'),
       (109, 'San Fernando', 'Buenos Aires'),
       (110, 'Formosa', 'Formosa'),
       (111, 'Las Heras', 'Mendoza'),
       (112, 'La Rioja', 'La Rioja'),
       (113, 'San Fernando del Valle de Cata', 'Catamarca'),
       (114, 'R?o Cuarto', 'C?rdoba'),
       (115, 'Comodoro Rivadavia', 'Chubut'),
       (116, 'Mendoza', 'Mendoza'),
       (117, 'San Nicol?s de los Arroyos', 'Buenos Aires'),
       (118, 'San Juan', 'San Juan'),
       (119, 'Escobar', 'Buenos Aires'),
       (120, 'Concordia', 'Entre Rios'),
       (121, 'Pilar', 'Buenos Aires'),
       (122, 'San Luis', 'San Luis'),
       (123, 'Ezeiza', 'Buenos Aires'),
       (124, 'San Rafael', 'Mendoza'),
       (125, 'Tandil', 'Buenos Aires'),
       (126, 'Yerevan', 'Yerevan'),
       (127, 'Gjumri', '?irak'),
       (128, 'Vanadzor', 'Lori'),
       (129, 'Oranjestad', '?'),
       (130, 'Sydney', 'New South Wales'),
       (131, 'Melbourne', 'Victoria'),
       (132, 'Brisbane', 'Queensland'),
       (133, 'Perth', 'West Australia'),
       (134, 'Adelaide', 'South Australia'),
       (135, 'Canberra', 'Capital Region'),
       (136, 'Gold Coast', 'Queensland'),
       (137, 'Newcastle', 'New South Wales'),
       (138, 'Central Coast', 'New South Wales'),
       (139, 'Wollongong', 'New South Wales'),
       (140, 'Hobart', 'Tasmania'),
       (141, 'Geelong', 'Victoria'),
       (142, 'Townsville', 'Queensland'),
       (143, 'Cairns', 'Queensland'),
       (144, 'Baku', 'Baki'),
       (145, 'G?nc', 'G?nc'),
       (146, 'Sumqayit', 'Sumqayit'),
       (147, 'Ming??evir', 'Ming??evir'),
       (148, 'Nassau', 'New Providence'),
       (149, 'al-Manama', 'al-Manama'),
       (150, 'Dhaka', 'Dhaka'),
       (151, 'Chittagong', 'Chittagong'),
       (152, 'Khulna', 'Khulna'),
       (153, 'Rajshahi', 'Rajshahi'),
       (154, 'Narayanganj', 'Dhaka'),
       (155, 'Rangpur', 'Rajshahi'),
       (156, 'Mymensingh', 'Dhaka'),
       (157, 'Barisal', 'Barisal'),
       (158, 'Tungi', 'Dhaka'),
       (159, 'Jessore', 'Khulna'),
       (160, 'Comilla', 'Chittagong'),
       (161, 'Nawabganj', 'Rajshahi'),
       (162, 'Dinajpur', 'Rajshahi'),
       (163, 'Bogra', 'Rajshahi'),
       (164, 'Sylhet', 'Sylhet'),
       (165, 'Brahmanbaria', 'Chittagong'),
       (166, 'Tangail', 'Dhaka'),
       (167, 'Jamalpur', 'Dhaka'),
       (168, 'Pabna', 'Rajshahi'),
       (169, 'Naogaon', 'Rajshahi'),
       (170, 'Sirajganj', 'Rajshahi'),
       (171, 'Narsinghdi', 'Dhaka'),
       (172, 'Saidpur', 'Rajshahi'),
       (173, 'Gazipur', 'Dhaka'),
       (174, 'Bridgetown', 'St Michael'),
       (175, 'Antwerpen', 'Antwerpen'),
       (176, 'Gent', 'East Flanderi'),
       (177, 'Charleroi', 'Hainaut'),
       (178, 'Li?ge', 'Li?ge'),
       (179, 'Bruxelles [Brussel]', 'Bryssel'),
       (180, 'Brugge', 'West Flanderi'),
       (181, 'Schaerbeek', 'Bryssel'),
       (182, 'Namur', 'Namur'),
       (183, 'Mons', 'Hainaut'),
       (184, 'Belize City', 'Belize City'),
       (185, 'Belmopan', 'Cayo'),
       (186, 'Cotonou', 'Atlantique'),
       (187, 'Porto-Novo', 'Ou?m'),
       (188, 'Djougou', 'Atacora'),
       (189, 'Parakou', 'Borgou'),
       (190, 'Saint George', 'Saint George?s'),
       (191, 'Hamilton', 'Hamilton'),
       (192, 'Thimphu', 'Thimphu'),
       (193, 'Santa Cruz de la Sierra', 'Santa Cruz'),
       (194, 'La Paz', 'La Paz'),
       (195, 'El Alto', 'La Paz'),
       (196, 'Cochabamba', 'Cochabamba'),
       (197, 'Oruro', 'Oruro'),
       (198, 'Sucre', 'Chuquisaca'),
       (199, 'Potos', 'Potos'),
       (200, 'Tarija', 'Tarija'),
       (201, 'Sarajevo', 'Federaatio'),
       (202, 'Banja Luka', 'Republika Srpska'),
       (203, 'Zenica', 'Federaatio'),
       (204, 'Gaborone', 'Gaborone'),
       (205, 'Francistown', 'Francistown'),
       (206, 'S?o Paulo', 'S?o Paulo'),
       (207, 'Rio de Janeiro', 'Rio de Janeiro'),
       (208, 'Salvador', 'Bahia'),
       (209, 'Belo Horizonte', 'Minas Gerais'),
       (210, 'Fortaleza', 'Cear'),
       (211, 'Bras?lia', 'Distrito Federal'),
       (212, 'Curitiba', 'Paran'),
       (213, 'Recife', 'Pernambuco'),
       (214, 'Porto Alegre', 'Rio Grande do Sul'),
       (215, 'Manaus', 'Amazonas'),
       (216, 'Bel', 'Par'),
       (217, 'Guarulhos', 'S?o Paulo'),
       (218, 'Goi?nia', 'Goi'),
       (219, 'Campinas', 'S?o Paulo'),
       (220, 'S?o Gon?alo', 'Rio de Janeiro'),
       (221, 'Nova Igua', 'Rio de Janeiro'),
       (222, 'S?o Lu', 'Maranh'),
       (223, 'Macei', 'Alagoas'),
       (224, 'Duque de Caxias', 'Rio de Janeiro'),
       (225, 'S?o Bernardo do Campo', 'S?o Paulo'),
       (226, 'Teresina', 'Piau'),
       (227, 'Natal', 'Rio Grande do Norte'),
       (228, 'Osasco', 'S?o Paulo'),
       (229, 'Campo Grande', 'Mato Grosso do Sul'),
       (230, 'Santo Andr', 'S?o Paulo'),
       (231, 'Jo?o Pessoa', 'Para?ba'),
       (232, 'Jaboat?o dos Guararapes', 'Pernambuco'),
       (233, 'Contagem', 'Minas Gerais'),
       (234, 'S?o Jos? dos Campos', 'S?o Paulo'),
       (235, 'Uberl?ndia', 'Minas Gerais'),
       (236, 'Feira de Santana', 'Bahia'),
       (237, 'Ribeir?o Preto', 'S?o Paulo'),
       (238, 'Sorocaba', 'S?o Paulo'),
       (239, 'Niter', 'Rio de Janeiro'),
       (240, 'Cuiab', 'Mato Grosso'),
       (241, 'Juiz de Fora', 'Minas Gerais'),
       (242, 'Aracaju', 'Sergipe'),
       (243, 'S?o Jo?o de Meriti', 'Rio de Janeiro'),
       (244, 'Londrina', 'Paran'),
       (245, 'Joinville', 'Santa Catarina'),
       (246, 'Belford Roxo', 'Rio de Janeiro'),
       (247, 'Santos', 'S?o Paulo'),
       (248, 'Ananindeua', 'Par'),
       (249, 'Campos dos Goytacazes', 'Rio de Janeiro'),
       (250, 'Mau', 'S?o Paulo'),
       (251, 'Carapicu?ba', 'S?o Paulo'),
       (252, 'Olinda', 'Pernambuco'),
       (253, 'Campina Grande', 'Para?ba'),
       (254, 'S?o Jos? do Rio Preto', 'S?o Paulo'),
       (255, 'Caxias do Sul', 'Rio Grande do Sul'),
       (256, 'Moji das Cruzes', 'S?o Paulo'),
       (257, 'Diadema', 'S?o Paulo'),
       (258, 'Aparecida de Goi?nia', 'Goi'),
       (259, 'Piracicaba', 'S?o Paulo'),
       (260, 'Cariacica', 'Esp?rito Santo'),
       (261, 'Vila Velha', 'Esp?rito Santo'),
       (262, 'Pelotas', 'Rio Grande do Sul'),
       (263, 'Bauru', 'S?o Paulo'),
       (264, 'Porto Velho', 'Rond?nia'),
       (265, 'Serra', 'Esp?rito Santo'),
       (266, 'Betim', 'Minas Gerais'),
       (267, 'Jund?a', 'S?o Paulo'),
       (268, 'Canoas', 'Rio Grande do Sul'),
       (269, 'Franca', 'S?o Paulo'),
       (270, 'S?o Vicente', 'S?o Paulo'),
       (271, 'Maring', 'Paran'),
       (272, 'Montes Claros', 'Minas Gerais'),
       (273, 'An?polis', 'Goi'),
       (274, 'Florian?polis', 'Santa Catarina'),
       (275, 'Petr?polis', 'Rio de Janeiro'),
       (276, 'Itaquaquecetuba', 'S?o Paulo'),
       (277, 'Vit?ria', 'Esp?rito Santo'),
       (278, 'Ponta Grossa', 'Paran'),
       (279, 'Rio Branco', 'Acre'),
       (280, 'Foz do Igua', 'Paran'),
       (281, 'Macap', 'Amap'),
       (282, 'Ilh?us', 'Bahia'),
       (283, 'Vit?ria da Conquista', 'Bahia'),
       (284, 'Uberaba', 'Minas Gerais'),
       (285, 'Paulista', 'Pernambuco'),
       (286, 'Limeira', 'S?o Paulo'),
       (287, 'Blumenau', 'Santa Catarina'),
       (288, 'Caruaru', 'Pernambuco'),
       (289, 'Santar', 'Par'),
       (290, 'Volta Redonda', 'Rio de Janeiro'),
       (291, 'Novo Hamburgo', 'Rio Grande do Sul'),
       (292, 'Caucaia', 'Cear'),
       (293, 'Santa Maria', 'Rio Grande do Sul'),
       (294, 'Cascavel', 'Paran'),
       (295, 'Guaruj', 'S?o Paulo'),
       (296, 'Ribeir?o das Neves', 'Minas Gerais'),
       (297, 'Governador Valadares', 'Minas Gerais'),
       (298, 'Taubat', 'S?o Paulo'),
       (299, 'Imperatriz', 'Maranh'),
       (300, 'Gravata', 'Rio Grande do Sul'),
       (301, 'Embu', 'S?o Paulo'),
       (302, 'Mossor', 'Rio Grande do Norte'),
       (303, 'V?rzea Grande', 'Mato Grosso'),
       (304, 'Petrolina', 'Pernambuco'),
       (305, 'Barueri', 'S?o Paulo'),
       (306, 'Viam', 'Rio Grande do Sul'),
       (307, 'Ipatinga', 'Minas Gerais'),
       (308, 'Juazeiro', 'Bahia'),
       (309, 'Juazeiro do Norte', 'Cear'),
       (310, 'Tabo?o da Serra', 'S?o Paulo'),
       (311, 'S?o Jos? dos Pinhais', 'Paran'),
       (312, 'Mag', 'Rio de Janeiro'),
       (313, 'Suzano', 'S?o Paulo'),
       (314, 'S?o Leopoldo', 'Rio Grande do Sul'),
       (315, 'Mar?lia', 'S?o Paulo'),
       (316, 'S?o Carlos', 'S?o Paulo'),
       (317, 'Sumar', 'S?o Paulo'),
       (318, 'Presidente Prudente', 'S?o Paulo'),
       (319, 'Divin?polis', 'Minas Gerais'),
       (320, 'Sete Lagoas', 'Minas Gerais'),
       (321, 'Rio Grande', 'Rio Grande do Sul'),
       (322, 'Itabuna', 'Bahia'),
       (323, 'Jequi', 'Bahia'),
       (324, 'Arapiraca', 'Alagoas'),
       (325, 'Colombo', 'Paran'),
       (326, 'Americana', 'S?o Paulo'),
       (327, 'Alvorada', 'Rio Grande do Sul'),
       (328, 'Araraquara', 'S?o Paulo'),
       (329, 'Itabora', 'Rio de Janeiro'),
       (330, 'Santa B?rbara d?Oeste', 'S?o Paulo'),
       (331, 'Nova Friburgo', 'Rio de Janeiro'),
       (332, 'Jacare', 'S?o Paulo'),
       (333, 'Ara?atuba', 'S?o Paulo'),
       (334, 'Barra Mansa', 'Rio de Janeiro'),
       (335, 'Praia Grande', 'S?o Paulo'),
       (336, 'Marab', 'Par'),
       (337, 'Crici?ma', 'Santa Catarina'),
       (338, 'Boa Vista', 'Roraima'),
       (339, 'Passo Fundo', 'Rio Grande do Sul'),
       (340, 'Dourados', 'Mato Grosso do Sul'),
       (341, 'Santa Luzia', 'Minas Gerais'),
       (342, 'Rio Claro', 'S?o Paulo'),
       (343, 'Maracana?', 'Cear'),
       (344, 'Guarapuava', 'Paran'),
       (345, 'Rondon?polis', 'Mato Grosso'),
       (346, 'S?o Jos', 'Santa Catarina'),
       (347, 'Cachoeiro de Itapemirim', 'Esp?rito Santo'),
       (348, 'Nil?polis', 'Rio de Janeiro'),
       (349, 'Itapevi', 'S?o Paulo'),
       (350, 'Cabo de Santo Agostinho', 'Pernambuco'),
       (351, 'Cama?ari', 'Bahia'),
       (352, 'Sobral', 'Cear'),
       (353, 'Itaja', 'Santa Catarina'),
       (354, 'Chapec', 'Santa Catarina'),
       (355, 'Cotia', 'S?o Paulo'),
       (356, 'Lages', 'Santa Catarina'),
       (357, 'Ferraz de Vasconcelos', 'S?o Paulo'),
       (358, 'Indaiatuba', 'S?o Paulo'),
       (359, 'Hortol?ndia', 'S?o Paulo'),
       (360, 'Caxias', 'Maranh'),
       (361, 'S?o Caetano do Sul', 'S?o Paulo'),
       (362, 'Itu', 'S?o Paulo'),
       (363, 'Nossa Senhora do Socorro', 'Sergipe'),
       (364, 'Parna?ba', 'Piau'),
       (365, 'Po?os de Caldas', 'Minas Gerais'),
       (366, 'Teres?polis', 'Rio de Janeiro'),
       (367, 'Barreiras', 'Bahia'),
       (368, 'Castanhal', 'Par'),
       (369, 'Alagoinhas', 'Bahia'),
       (370, 'Itapecerica da Serra', 'S?o Paulo'),
       (371, 'Uruguaiana', 'Rio Grande do Sul'),
       (372, 'Paranagu', 'Paran'),
       (373, 'Ibirit', 'Minas Gerais'),
       (374, 'Timon', 'Maranh'),
       (375, 'Luzi?nia', 'Goi'),
       (376, 'Maca', 'Rio de Janeiro'),
       (377, 'Te?filo Otoni', 'Minas Gerais'),
       (378, 'Moji-Gua', 'S?o Paulo'),
       (379, 'Palmas', 'Tocantins'),
       (380, 'Pindamonhangaba', 'S?o Paulo'),
       (381, 'Francisco Morato', 'S?o Paulo'),
       (382, 'Bag', 'Rio Grande do Sul'),
       (383, 'Sapucaia do Sul', 'Rio Grande do Sul'),
       (384, 'Cabo Frio', 'Rio de Janeiro'),
       (385, 'Itapetininga', 'S?o Paulo'),
       (386, 'Patos de Minas', 'Minas Gerais'),
       (387, 'Camaragibe', 'Pernambuco'),
       (388, 'Bragan?a Paulista', 'S?o Paulo'),
       (389, 'Queimados', 'Rio de Janeiro'),
       (390, 'Aragua?na', 'Tocantins'),
       (391, 'Garanhuns', 'Pernambuco'),
       (392, 'Vit?ria de Santo Ant', 'Pernambuco'),
       (393, 'Santa Rita', 'Para?ba'),
       (394, 'Barbacena', 'Minas Gerais'),
       (395, 'Abaetetuba', 'Par'),
       (396, 'Ja?', 'S?o Paulo'),
       (397, 'Lauro de Freitas', 'Bahia'),
       (398, 'Franco da Rocha', 'S?o Paulo'),
       (399, 'Teixeira de Freitas', 'Bahia'),
       (400, 'Varginha', 'Minas Gerais'),
       (401, 'Ribeir?o Pires', 'S?o Paulo'),
       (402, 'Sabar', 'Minas Gerais'),
       (403, 'Catanduva', 'S?o Paulo'),
       (404, 'Rio Verde', 'Goi'),
       (405, 'Botucatu', 'S?o Paulo'),
       (406, 'Colatina', 'Esp?rito Santo'),
       (407, 'Santa Cruz do Sul', 'Rio Grande do Sul'),
       (408, 'Linhares', 'Esp?rito Santo'),
       (409, 'Apucarana', 'Paran'),
       (410, 'Barretos', 'S?o Paulo'),
       (411, 'Guaratinguet', 'S?o Paulo'),
       (412, 'Cachoeirinha', 'Rio Grande do Sul'),
       (413, 'Cod', 'Maranh'),
       (414, 'Jaragu? do Sul', 'Santa Catarina'),
       (415, 'Cubat', 'S?o Paulo'),
       (416, 'Itabira', 'Minas Gerais'),
       (417, 'Itaituba', 'Par'),
       (418, 'Araras', 'S?o Paulo'),
       (419, 'Resende', 'Rio de Janeiro'),
       (420, 'Atibaia', 'S?o Paulo'),
       (421, 'Pouso Alegre', 'Minas Gerais'),
       (422, 'Toledo', 'Paran'),
       (423, 'Crato', 'Cear'),
       (424, 'Passos', 'Minas Gerais'),
       (425, 'Araguari', 'Minas Gerais'),
       (426, 'S?o Jos? de Ribamar', 'Maranh'),
       (427, 'Pinhais', 'Paran'),
       (428, 'Sert?ozinho', 'S?o Paulo'),
       (429, 'Conselheiro Lafaiete', 'Minas Gerais'),
       (430, 'Paulo Afonso', 'Bahia'),
       (431, 'Angra dos Reis', 'Rio de Janeiro'),
       (432, 'Eun?polis', 'Bahia'),
       (433, 'Salto', 'S?o Paulo'),
       (434, 'Ourinhos', 'S?o Paulo'),
       (435, 'Parnamirim', 'Rio Grande do Norte'),
       (436, 'Jacobina', 'Bahia'),
       (437, 'Coronel Fabriciano', 'Minas Gerais'),
       (438, 'Birigui', 'S?o Paulo'),
       (439, 'Tatu', 'S?o Paulo'),
       (440, 'Ji-Paran', 'Rond?nia'),
       (441, 'Bacabal', 'Maranh'),
       (442, 'Camet', 'Par'),
       (443, 'Gua?ba', 'Rio Grande do Sul'),
       (444, 'S?o Louren?o da Mata', 'Pernambuco'),
       (445, 'Santana do Livramento', 'Rio Grande do Sul'),
       (446, 'Votorantim', 'S?o Paulo'),
       (447, 'Campo Largo', 'Paran'),
       (448, 'Patos', 'Para?ba'),
       (449, 'Ituiutaba', 'Minas Gerais'),
       (450, 'Corumb', 'Mato Grosso do Sul'),
       (451, 'Palho', 'Santa Catarina'),
       (452, 'Barra do Pira', 'Rio de Janeiro'),
       (453, 'Bento Gon?alves', 'Rio Grande do Sul'),
       (454, 'Po', 'S?o Paulo'),
       (455, '?guas Lindas de Goi', 'Goi'),
       (456, 'London', 'England'),
       (457, 'Birmingham', 'England'),
       (458, 'Glasgow', 'Scotland'),
       (459, 'Liverpool', 'England'),
       (460, 'Edinburgh', 'Scotland'),
       (461, 'Sheffield', 'England'),
       (462, 'Manchester', 'England'),
       (463, 'Leeds', 'England'),
       (464, 'Bristol', 'England'),
       (465, 'Cardiff', 'Wales'),
       (466, 'Coventry', 'England'),
       (467, 'Leicester', 'England'),
       (468, 'Bradford', 'England'),
       (469, 'Belfast', 'North Ireland'),
       (470, 'Nottingham', 'England'),
       (471, 'Kingston upon Hull', 'England'),
       (472, 'Plymouth', 'England'),
       (473, 'Stoke-on-Trent', 'England'),
       (474, 'Wolverhampton', 'England'),
       (475, 'Derby', 'England'),
       (476, 'Swansea', 'Wales'),
       (477, 'Southampton', 'England'),
       (478, 'Aberdeen', 'Scotland'),
       (479, 'Northampton', 'England'),
       (480, 'Dudley', 'England'),
       (481, 'Portsmouth', 'England'),
       (482, 'Newcastle upon Tyne', 'England'),
       (483, 'Sunderland', 'England'),
       (484, 'Luton', 'England'),
       (485, 'Swindon', 'England'),
       (486, 'Southend-on-Sea', 'England'),
       (487, 'Walsall', 'England'),
       (488, 'Bournemouth', 'England'),
       (489, 'Peterborough', 'England'),
       (490, 'Brighton', 'England'),
       (491, 'Blackpool', 'England'),
       (492, 'Dundee', 'Scotland'),
       (493, 'West Bromwich', 'England'),
       (494, 'Reading', 'England'),
       (495, 'Oldbury/Smethwick (Warley)', 'England'),
       (496, 'Middlesbrough', 'England'),
       (497, 'Huddersfield', 'England'),
       (498, 'Oxford', 'England'),
       (499, 'Poole', 'England'),
       (500, 'Bolton', 'England'),
       (501, 'Blackburn', 'England'),
       (502, 'Newport', 'Wales'),
       (503, 'Preston', 'England'),
       (504, 'Stockport', 'England'),
       (505, 'Norwich', 'England'),
       (506, 'Rotherham', 'England'),
       (507, 'Cambridge', 'England'),
       (508, 'Watford', 'England'),
       (509, 'Ipswich', 'England'),
       (510, 'Slough', 'England'),
       (511, 'Exeter', 'England'),
       (512, 'Cheltenham', 'England'),
       (513, 'Gloucester', 'England'),
       (514, 'Saint Helens', 'England'),
       (515, 'Sutton Coldfield', 'England'),
       (516, 'York', 'England'),
       (517, 'Oldham', 'England'),
       (518, 'Basildon', 'England'),
       (519, 'Worthing', 'England'),
       (520, 'Chelmsford', 'England'),
       (521, 'Colchester', 'England'),
       (522, 'Crawley', 'England'),
       (523, 'Gillingham', 'England'),
       (524, 'Solihull', 'England'),
       (525, 'Rochdale', 'England'),
       (526, 'Birkenhead', 'England'),
       (527, 'Worcester', 'England'),
       (528, 'Hartlepool', 'England'),
       (529, 'Halifax', 'England'),
       (530, 'Woking/Byfleet', 'England'),
       (531, 'Southport', 'England'),
       (532, 'Maidstone', 'England'),
       (533, 'Eastbourne', 'England'),
       (534, 'Grimsby', 'England'),
       (535, 'Saint Helier', 'Jersey'),
       (536, 'Douglas', '?'),
       (537, 'Road Town', 'Tortola'),
       (538, 'Bandar Seri Begawan', 'Brunei and Muara'),
       (539, 'Sofija', 'Grad Sofija'),
       (540, 'Plovdiv', 'Plovdiv'),
       (541, 'Varna', 'Varna'),
       (542, 'Burgas', 'Burgas'),
       (543, 'Ruse', 'Ruse'),
       (544, 'Stara Zagora', 'Haskovo'),
       (545, 'Pleven', 'Lovec'),
       (546, 'Sliven', 'Burgas'),
       (547, 'Dobric', 'Varna'),
       (548, '?umen', 'Varna'),
       (549, 'Ouagadougou', 'Kadiogo'),
       (550, 'Bobo-Dioulasso', 'Houet'),
       (551, 'Koudougou', 'Boulkiemd'),
       (552, 'Bujumbura', 'Bujumbura'),
       (553, 'George Town', 'Grand Cayman'),
       (554, 'Santiago de Chile', 'Santiago'),
       (555, 'Puente Alto', 'Santiago'),
       (556, 'Vi?a del Mar', 'Valpara?so'),
       (557, 'Valpara?so', 'Valpara?so'),
       (558, 'Talcahuano', 'B?ob'),
       (559, 'Antofagasta', 'Antofagasta'),
       (560, 'San Bernardo', 'Santiago'),
       (561, 'Temuco', 'La Araucan'),
       (562, 'Concepci', 'B?ob'),
       (563, 'Rancagua', 'O?Higgins'),
       (564, 'Arica', 'Tarapac'),
       (565, 'Talca', 'Maule'),
       (566, 'Chill', 'B?ob'),
       (567, 'Iquique', 'Tarapac'),
       (568, 'Los Angeles', 'B?ob'),
       (569, 'Puerto Montt', 'Los Lagos'),
       (570, 'Coquimbo', 'Coquimbo'),
       (571, 'Osorno', 'Los Lagos'),
       (572, 'La Serena', 'Coquimbo'),
       (573, 'Calama', 'Antofagasta'),
       (574, 'Valdivia', 'Los Lagos'),
       (575, 'Punta Arenas', 'Magallanes'),
       (576, 'Copiap', 'Atacama'),
       (577, 'Quilpu', 'Valpara?so'),
       (578, 'Curic', 'Maule'),
       (579, 'Ovalle', 'Coquimbo'),
       (580, 'Coronel', 'B?ob'),
       (581, 'San Pedro de la Paz', 'B?ob'),
       (582, 'Melipilla', 'Santiago'),
       (583, 'Avarua', 'Rarotonga'),
       (584, 'San Jos', 'San Jos'),
       (585, 'Djibouti', 'Djibouti'),
       (586, 'Roseau', 'St George'),
       (587, 'Santo Domingo de Guzm', 'Distrito Nacional'),
       (588, 'Santiago de los Caballeros', 'Santiago'),
       (589, 'La Romana', 'La Romana'),
       (590, 'San Pedro de Macor', 'San Pedro de Macor'),
       (591, 'San Francisco de Macor', 'Duarte'),
       (592, 'San Felipe de Puerto Plata', 'Puerto Plata'),
       (593, 'Guayaquil', 'Guayas'),
       (594, 'Quito', 'Pichincha'),
       (595, 'Cuenca', 'Azuay'),
       (596, 'Machala', 'El Oro'),
       (597, 'Santo Domingo de los Colorados', 'Pichincha'),
       (598, 'Portoviejo', 'Manab'),
       (599, 'Ambato', 'Tungurahua'),
       (600, 'Manta', 'Manab'),
       (601, 'Duran [Eloy Alfaro]', 'Guayas'),
       (602, 'Ibarra', 'Imbabura'),
       (603, 'Quevedo', 'Los R?os'),
       (604, 'Milagro', 'Guayas'),
       (605, 'Loja', 'Loja'),
       (606, 'R?obamba', 'Chimborazo'),
       (607, 'Esmeraldas', 'Esmeraldas'),
       (608, 'Cairo', 'Kairo'),
       (609, 'Alexandria', 'Aleksandria'),
       (610, 'Giza', 'Giza'),
       (611, 'Shubra al-Khayma', 'al-Qalyubiya'),
       (612, 'Port Said', 'Port Said'),
       (613, 'Suez', 'Suez'),
       (614, 'al-Mahallat al-Kubra', 'al-Gharbiya'),
       (615, 'Tanta', 'al-Gharbiya'),
       (616, 'al-Mansura', 'al-Daqahliya'),
       (617, 'Luxor', 'Luxor'),
       (618, 'Asyut', 'Asyut'),
       (619, 'Bahtim', 'al-Qalyubiya'),
       (620, 'Zagazig', 'al-Sharqiya'),
       (621, 'al-Faiyum', 'al-Faiyum'),
       (622, 'Ismailia', 'Ismailia'),
       (623, 'Kafr al-Dawwar', 'al-Buhayra'),
       (624, 'Assuan', 'Assuan'),
       (625, 'Damanhur', 'al-Buhayra'),
       (626, 'al-Minya', 'al-Minya'),
       (627, 'Bani Suwayf', 'Bani Suwayf'),
       (628, 'Qina', 'Qina'),
       (629, 'Sawhaj', 'Sawhaj'),
       (630, 'Shibin al-Kawm', 'al-Minufiya'),
       (631, 'Bulaq al-Dakrur', 'Giza'),
       (632, 'Banha', 'al-Qalyubiya'),
       (633, 'Warraq al-Arab', 'Giza'),
       (634, 'Kafr al-Shaykh', 'Kafr al-Shaykh'),
       (635, 'Mallawi', 'al-Minya'),
       (636, 'Bilbays', 'al-Sharqiya'),
       (637, 'Mit Ghamr', 'al-Daqahliya'),
       (638, 'al-Arish', 'Shamal Sina'),
       (639, 'Talkha', 'al-Daqahliya'),
       (640, 'Qalyub', 'al-Qalyubiya'),
       (641, 'Jirja', 'Sawhaj'),
       (642, 'Idfu', 'Qina'),
       (643, 'al-Hawamidiya', 'Giza'),
       (644, 'Disuq', 'Kafr al-Shaykh'),
       (645, 'San Salvador', 'San Salvador'),
       (646, 'Santa Ana', 'Santa Ana'),
       (647, 'Mejicanos', 'San Salvador'),
       (648, 'Soyapango', 'San Salvador'),
       (649, 'San Miguel', 'San Miguel'),
       (650, 'Nueva San Salvador', 'La Libertad'),
       (651, 'Apopa', 'San Salvador'),
       (652, 'Asmara', 'Maekel'),
       (653, 'Madrid', 'Madrid'),
       (654, 'Barcelona', 'Katalonia'),
       (655, 'Valencia', 'Valencia'),
       (656, 'Sevilla', 'Andalusia'),
       (657, 'Zaragoza', 'Aragonia'),
       (658, 'M?laga', 'Andalusia'),
       (659, 'Bilbao', 'Baskimaa'),
       (660, 'Las Palmas de Gran Canaria', 'Canary Islands'),
       (661, 'Murcia', 'Murcia'),
       (662, 'Palma de Mallorca', 'Balears'),
       (663, 'Valladolid', 'Castilla and Le'),
       (664, 'C?rdoba', 'Andalusia'),
       (665, 'Vigo', 'Galicia'),
       (666, 'Alicante [Alacant]', 'Valencia'),
       (667, 'Gij', 'Asturia'),
       (668, 'L?Hospitalet de Llobregat', 'Katalonia'),
       (669, 'Granada', 'Andalusia'),
       (670, 'A Coru?a (La Coru', 'Galicia'),
       (671, 'Vitoria-Gasteiz', 'Baskimaa'),
       (672, 'Santa Cruz de Tenerife', 'Canary Islands'),
       (673, 'Badalona', 'Katalonia'),
       (674, 'Oviedo', 'Asturia'),
       (675, 'M?stoles', 'Madrid'),
       (676, 'Elche [Elx]', 'Valencia'),
       (677, 'Sabadell', 'Katalonia'),
       (678, 'Santander', 'Cantabria'),
       (679, 'Jerez de la Frontera', 'Andalusia'),
       (680, 'Pamplona [Iru', 'Navarra'),
       (681, 'Donostia-San Sebasti', 'Baskimaa'),
       (682, 'Cartagena', 'Murcia'),
       (683, 'Legan', 'Madrid'),
       (684, 'Fuenlabrada', 'Madrid'),
       (685, 'Almer', 'Andalusia'),
       (686, 'Terrassa', 'Katalonia'),
       (687, 'Alcal? de Henares', 'Madrid'),
       (688, 'Burgos', 'Castilla and Le'),
       (689, 'Salamanca', 'Castilla and Le'),
       (690, 'Albacete', 'Kastilia-La Mancha'),
       (691, 'Getafe', 'Madrid'),
       (692, 'C?diz', 'Andalusia'),
       (693, 'Alcorc', 'Madrid'),
       (694, 'Huelva', 'Andalusia'),
       (695, 'Le', 'Castilla and Le'),
       (696, 'Castell?n de la Plana [Castell', 'Valencia'),
       (697, 'Badajoz', 'Extremadura'),
       (698, '[San Crist?bal de] la Laguna', 'Canary Islands'),
       (699, 'Logro', 'La Rioja'),
       (700, 'Santa Coloma de Gramenet', 'Katalonia'),
       (701, 'Tarragona', 'Katalonia'),
       (702, 'Lleida (L?rida)', 'Katalonia'),
       (703, 'Ja', 'Andalusia'),
       (704, 'Ourense (Orense)', 'Galicia'),
       (705, 'Matar', 'Katalonia'),
       (706, 'Algeciras', 'Andalusia'),
       (707, 'Marbella', 'Andalusia'),
       (708, 'Barakaldo', 'Baskimaa'),
       (709, 'Dos Hermanas', 'Andalusia'),
       (710, 'Santiago de Compostela', 'Galicia'),
       (711, 'Torrej?n de Ardoz', 'Madrid'),
       (712, 'Cape Town', 'Western Cape'),
       (713, 'Soweto', 'Gauteng'),
       (714, 'Johannesburg', 'Gauteng'),
       (715, 'Port Elizabeth', 'Eastern Cape'),
       (716, 'Pretoria', 'Gauteng'),
       (717, 'Inanda', 'KwaZulu-Natal'),
       (718, 'Durban', 'KwaZulu-Natal'),
       (719, 'Vanderbijlpark', 'Gauteng'),
       (720, 'Kempton Park', 'Gauteng'),
       (721, 'Alberton', 'Gauteng'),
       (722, 'Pinetown', 'KwaZulu-Natal'),
       (723, 'Pietermaritzburg', 'KwaZulu-Natal'),
       (724, 'Benoni', 'Gauteng'),
       (725, 'Randburg', 'Gauteng'),
       (726, 'Umlazi', 'KwaZulu-Natal'),
       (727, 'Bloemfontein', 'Free State'),
       (728, 'Vereeniging', 'Gauteng'),
       (729, 'Wonderboom', 'Gauteng'),
       (730, 'Roodepoort', 'Gauteng'),
       (731, 'Boksburg', 'Gauteng'),
       (732, 'Klerksdorp', 'North West'),
       (733, 'Soshanguve', 'Gauteng'),
       (734, 'Newcastle', 'KwaZulu-Natal'),
       (735, 'East London', 'Eastern Cape'),
       (736, 'Welkom', 'Free State'),
       (737, 'Kimberley', 'Northern Cape'),
       (738, 'Uitenhage', 'Eastern Cape'),
       (739, 'Chatsworth', 'KwaZulu-Natal'),
       (740, 'Mdantsane', 'Eastern Cape'),
       (741, 'Krugersdorp', 'Gauteng'),
       (742, 'Botshabelo', 'Free State'),
       (743, 'Brakpan', 'Gauteng'),
       (744, 'Witbank', 'Mpumalanga'),
       (745, 'Oberholzer', 'Gauteng'),
       (746, 'Germiston', 'Gauteng'),
       (747, 'Springs', 'Gauteng'),
       (748, 'Westonaria', 'Gauteng'),
       (749, 'Randfontein', 'Gauteng'),
       (750, 'Paarl', 'Western Cape'),
       (751, 'Potchefstroom', 'North West'),
       (752, 'Rustenburg', 'North West'),
       (753, 'Nigel', 'Gauteng'),
       (754, 'George', 'Western Cape'),
       (755, 'Ladysmith', 'KwaZulu-Natal'),
       (756, 'Addis Abeba', 'Addis Abeba'),
       (757, 'Dire Dawa', 'Dire Dawa'),
       (758, 'Nazret', 'Oromia'),
       (759, 'Gonder', 'Amhara'),
       (760, 'Dese', 'Amhara'),
       (761, 'Mekele', 'Tigray'),
       (762, 'Bahir Dar', 'Amhara'),
       (763, 'Stanley', 'East Falkland'),
       (764, 'Suva', 'Central'),
       (765, 'Quezon', 'National Capital Reg'),
       (766, 'Manila', 'National Capital Reg'),
       (767, 'Kalookan', 'National Capital Reg'),
       (768, 'Davao', 'Southern Mindanao'),
       (769, 'Cebu', 'Central Visayas'),
       (770, 'Zamboanga', 'Western Mindanao'),
       (771, 'Pasig', 'National Capital Reg'),
       (772, 'Valenzuela', 'National Capital Reg'),
       (773, 'Las Pi', 'National Capital Reg'),
       (774, 'Antipolo', 'Southern Tagalog'),
       (775, 'Taguig', 'National Capital Reg'),
       (776, 'Cagayan de Oro', 'Northern Mindanao'),
       (777, 'Para?aque', 'National Capital Reg'),
       (778, 'Makati', 'National Capital Reg'),
       (779, 'Bacolod', 'Western Visayas'),
       (780, 'General Santos', 'Southern Mindanao'),
       (781, 'Marikina', 'National Capital Reg'),
       (782, 'Dasmari', 'Southern Tagalog'),
       (783, 'Muntinlupa', 'National Capital Reg'),
       (784, 'Iloilo', 'Western Visayas'),
       (785, 'Pasay', 'National Capital Reg'),
       (786, 'Malabon', 'National Capital Reg'),
       (787, 'San Jos? del Monte', 'Central Luzon'),
       (788, 'Bacoor', 'Southern Tagalog'),
       (789, 'Iligan', 'Central Mindanao'),
       (790, 'Calamba', 'Southern Tagalog'),
       (791, 'Mandaluyong', 'National Capital Reg'),
       (792, 'Butuan', 'Caraga'),
       (793, 'Angeles', 'Central Luzon'),
       (794, 'Tarlac', 'Central Luzon'),
       (795, 'Mandaue', 'Central Visayas'),
       (796, 'Baguio', 'CAR'),
       (797, 'Batangas', 'Southern Tagalog'),
       (798, 'Cainta', 'Southern Tagalog'),
       (799, 'San Pedro', 'Southern Tagalog'),
       (800, 'Navotas', 'National Capital Reg'),
       (801, 'Cabanatuan', 'Central Luzon'),
       (802, 'San Fernando', 'Central Luzon'),
       (803, 'Lipa', 'Southern Tagalog'),
       (804, 'Lapu-Lapu', 'Central Visayas'),
       (805, 'San Pablo', 'Southern Tagalog'),
       (806, 'Bi', 'Southern Tagalog'),
       (807, 'Taytay', 'Southern Tagalog'),
       (808, 'Lucena', 'Southern Tagalog'),
       (809, 'Imus', 'Southern Tagalog'),
       (810, 'Olongapo', 'Central Luzon'),
       (811, 'Binangonan', 'Southern Tagalog'),
       (812, 'Santa Rosa', 'Southern Tagalog'),
       (813, 'Tagum', 'Southern Mindanao'),
       (814, 'Tacloban', 'Eastern Visayas'),
       (815, 'Malolos', 'Central Luzon'),
       (816, 'Mabalacat', 'Central Luzon'),
       (817, 'Cotabato', 'Central Mindanao'),
       (818, 'Meycauayan', 'Central Luzon'),
       (819, 'Puerto Princesa', 'Southern Tagalog'),
       (820, 'Legazpi', 'Bicol'),
       (821, 'Silang', 'Southern Tagalog'),
       (822, 'Ormoc', 'Eastern Visayas'),
       (823, 'San Carlos', 'Ilocos'),
       (824, 'Kabankalan', 'Western Visayas'),
       (825, 'Talisay', 'Central Visayas'),
       (826, 'Valencia', 'Northern Mindanao'),
       (827, 'Calbayog', 'Eastern Visayas'),
       (828, 'Santa Maria', 'Central Luzon'),
       (829, 'Pagadian', 'Western Mindanao'),
       (830, 'Cadiz', 'Western Visayas'),
       (831, 'Bago', 'Western Visayas'),
       (832, 'Toledo', 'Central Visayas'),
       (833, 'Naga', 'Bicol'),
       (834, 'San Mateo', 'Southern Tagalog'),
       (835, 'Panabo', 'Southern Mindanao'),
       (836, 'Koronadal', 'Southern Mindanao'),
       (837, 'Marawi', 'Central Mindanao'),
       (838, 'Dagupan', 'Ilocos'),
       (839, 'Sagay', 'Western Visayas'),
       (840, 'Roxas', 'Western Visayas'),
       (841, 'Lubao', 'Central Luzon'),
       (842, 'Digos', 'Southern Mindanao'),
       (843, 'San Miguel', 'Central Luzon'),
       (844, 'Malaybalay', 'Northern Mindanao'),
       (845, 'Tuguegarao', 'Cagayan Valley'),
       (846, 'Ilagan', 'Cagayan Valley'),
       (847, 'Baliuag', 'Central Luzon'),
       (848, 'Surigao', 'Caraga'),
       (849, 'San Carlos', 'Western Visayas'),
       (850, 'San Juan del Monte', 'National Capital Reg'),
       (851, 'Tanauan', 'Southern Tagalog'),
       (852, 'Concepcion', 'Central Luzon'),
       (853, 'Rodriguez (Montalban)', 'Southern Tagalog'),
       (854, 'Sariaya', 'Southern Tagalog'),
       (855, 'Malasiqui', 'Ilocos'),
       (856, 'General Mariano Alvarez', 'Southern Tagalog'),
       (857, 'Urdaneta', 'Ilocos'),
       (858, 'Hagonoy', 'Central Luzon'),
       (859, 'San Jose', 'Southern Tagalog'),
       (860, 'Polomolok', 'Southern Mindanao'),
       (861, 'Santiago', 'Cagayan Valley'),
       (862, 'Tanza', 'Southern Tagalog'),
       (863, 'Ozamis', 'Northern Mindanao'),
       (864, 'Mexico', 'Central Luzon'),
       (865, 'San Jose', 'Central Luzon'),
       (866, 'Silay', 'Western Visayas'),
       (867, 'General Trias', 'Southern Tagalog'),
       (868, 'Tabaco', 'Bicol'),
       (869, 'Cabuyao', 'Southern Tagalog'),
       (870, 'Calapan', 'Southern Tagalog'),
       (871, 'Mati', 'Southern Mindanao'),
       (872, 'Midsayap', 'Central Mindanao'),
       (873, 'Cauayan', 'Cagayan Valley'),
       (874, 'Gingoog', 'Northern Mindanao'),
       (875, 'Dumaguete', 'Central Visayas'),
       (876, 'San Fernando', 'Ilocos'),
       (877, 'Arayat', 'Central Luzon'),
       (878, 'Bayawan (Tulong)', 'Central Visayas'),
       (879, 'Kidapawan', 'Central Mindanao'),
       (880, 'Daraga (Locsin)', 'Bicol'),
       (881, 'Marilao', 'Central Luzon'),
       (882, 'Malita', 'Southern Mindanao'),
       (883, 'Dipolog', 'Western Mindanao'),
       (884, 'Cavite', 'Southern Tagalog'),
       (885, 'Danao', 'Central Visayas'),
       (886, 'Bislig', 'Caraga'),
       (887, 'Talavera', 'Central Luzon'),
       (888, 'Guagua', 'Central Luzon'),
       (889, 'Bayambang', 'Ilocos'),
       (890, 'Nasugbu', 'Southern Tagalog'),
       (891, 'Baybay', 'Eastern Visayas'),
       (892, 'Capas', 'Central Luzon'),
       (893, 'Sultan Kudarat', 'ARMM'),
       (894, 'Laoag', 'Ilocos'),
       (895, 'Bayugan', 'Caraga'),
       (896, 'Malungon', 'Southern Mindanao'),
       (897, 'Santa Cruz', 'Southern Tagalog'),
       (898, 'Sorsogon', 'Bicol'),
       (899, 'Candelaria', 'Southern Tagalog'),
       (900, 'Ligao', 'Bicol'),
       (901, 'T?rshavn', 'Streymoyar'),
       (902, 'Libreville', 'Estuaire'),
       (903, 'Serekunda', 'Kombo St Mary'),
       (904, 'Banjul', 'Banjul'),
       (905, 'Tbilisi', 'Tbilisi'),
       (906, 'Kutaisi', 'Imereti'),
       (907, 'Rustavi', 'Kvemo Kartli'),
       (908, 'Batumi', 'Adzaria [At?ara]'),
       (909, 'Sohumi', 'Abhasia [Aphazeti]'),
       (910, 'Accra', 'Greater Accra'),
       (911, 'Kumasi', 'Ashanti'),
       (912, 'Tamale', 'Northern'),
       (913, 'Tema', 'Greater Accra'),
       (914, 'Sekondi-Takoradi', 'Western'),
       (915, 'Gibraltar', '?'),
       (916, 'Saint George?s', 'St George'),
       (917, 'Nuuk', 'Kitaa'),
       (918, 'Les Abymes', 'Grande-Terre'),
       (919, 'Basse-Terre', 'Basse-Terre'),
       (920, 'Tamuning', '?'),
       (921, 'Aga', '?'),
       (922, 'Ciudad de Guatemala', 'Guatemala'),
       (923, 'Mixco', 'Guatemala'),
       (924, 'Villa Nueva', 'Guatemala'),
       (925, 'Quetzaltenango', 'Quetzaltenango'),
       (926, 'Conakry', 'Conakry'),
       (927, 'Bissau', 'Bissau'),
       (928, 'Georgetown', 'Georgetown'),
       (929, 'Port-au-Prince', 'Ouest'),
       (930, 'Carrefour', 'Ouest'),
       (931, 'Delmas', 'Ouest'),
       (932, 'Le-Cap-Ha?tien', 'Nord'),
       (933, 'Tegucigalpa', 'Distrito Central'),
       (934, 'San Pedro Sula', 'Cort'),
       (935, 'La Ceiba', 'Atl?ntida'),
       (936, 'Kowloon and New Kowloon', 'Kowloon and New Kowl'),
       (937, 'Victoria', 'Hongkong'),
       (938, 'Longyearbyen', 'L?nsimaa'),
       (939, 'Jakarta', 'Jakarta Raya'),
       (940, 'Surabaya', 'East Java'),
       (941, 'Bandung', 'West Java'),
       (942, 'Medan', 'Sumatera Utara'),
       (943, 'Palembang', 'Sumatera Selatan'),
       (944, 'Tangerang', 'West Java'),
       (945, 'Semarang', 'Central Java'),
       (946, 'Ujung Pandang', 'Sulawesi Selatan'),
       (947, 'Malang', 'East Java'),
       (948, 'Bandar Lampung', 'Lampung'),
       (949, 'Bekasi', 'West Java'),
       (950, 'Padang', 'Sumatera Barat'),
       (951, 'Surakarta', 'Central Java'),
       (952, 'Banjarmasin', 'Kalimantan Selatan'),
       (953, 'Pekan Baru', 'Riau'),
       (954, 'Denpasar', 'Bali'),
       (955, 'Yogyakarta', 'Yogyakarta'),
       (956, 'Pontianak', 'Kalimantan Barat'),
       (957, 'Samarinda', 'Kalimantan Timur'),
       (958, 'Jambi', 'Jambi'),
       (959, 'Depok', 'West Java'),
       (960, 'Cimahi', 'West Java'),
       (961, 'Balikpapan', 'Kalimantan Timur'),
       (962, 'Manado', 'Sulawesi Utara'),
       (963, 'Mataram', 'Nusa Tenggara Barat'),
       (964, 'Pekalongan', 'Central Java'),
       (965, 'Tegal', 'Central Java'),
       (966, 'Bogor', 'West Java'),
       (967, 'Ciputat', 'West Java'),
       (968, 'Pondokgede', 'West Java'),
       (969, 'Cirebon', 'West Java'),
       (970, 'Kediri', 'East Java'),
       (971, 'Ambon', 'Molukit'),
       (972, 'Jember', 'East Java'),
       (973, 'Cilacap', 'Central Java'),
       (974, 'Cimanggis', 'West Java'),
       (975, 'Pematang Siantar', 'Sumatera Utara'),
       (976, 'Purwokerto', 'Central Java'),
       (977, 'Ciomas', 'West Java'),
       (978, 'Tasikmalaya', 'West Java'),
       (979, 'Madiun', 'East Java'),
       (980, 'Bengkulu', 'Bengkulu'),
       (981, 'Karawang', 'West Java'),
       (982, 'Banda Aceh', 'Aceh'),
       (983, 'Palu', 'Sulawesi Tengah'),
       (984, 'Pasuruan', 'East Java'),
       (985, 'Kupang', 'Nusa Tenggara Timur'),
       (986, 'Tebing Tinggi', 'Sumatera Utara'),
       (987, 'Percut Sei Tuan', 'Sumatera Utara'),
       (988, 'Binjai', 'Sumatera Utara'),
       (989, 'Sukabumi', 'West Java'),
       (990, 'Waru', 'East Java'),
       (991, 'Pangkal Pinang', 'Sumatera Selatan'),
       (992, 'Magelang', 'Central Java'),
       (993, 'Blitar', 'East Java'),
       (994, 'Serang', 'West Java'),
       (995, 'Probolinggo', 'East Java'),
       (996, 'Cilegon', 'West Java'),
       (997, 'Cianjur', 'West Java'),
       (998, 'Ciparay', 'West Java'),
       (999, 'Lhokseumawe', 'Aceh'),
       (1000, 'Taman', 'East Java'),
       (1001, 'Depok', 'Yogyakarta'),
       (1002, 'Citeureup', 'West Java'),
       (1003, 'Pemalang', 'Central Java'),
       (1004, 'Klaten', 'Central Java'),
       (1005, 'Salatiga', 'Central Java'),
       (1006, 'Cibinong', 'West Java'),
       (1007, 'Palangka Raya', 'Kalimantan Tengah'),
       (1008, 'Mojokerto', 'East Java'),
       (1009, 'Purwakarta', 'West Java'),
       (1010, 'Garut', 'West Java'),
       (1011, 'Kudus', 'Central Java'),
       (1012, 'Kendari', 'Sulawesi Tenggara'),
       (1013, 'Jaya Pura', 'West Irian'),
       (1014, 'Gorontalo', 'Sulawesi Utara'),
       (1015, 'Majalaya', 'West Java'),
       (1016, 'Pondok Aren', 'West Java'),
       (1017, 'Jombang', 'East Java'),
       (1018, 'Sunggal', 'Sumatera Utara'),
       (1019, 'Batam', 'Riau'),
       (1020, 'Padang Sidempuan', 'Sumatera Utara'),
       (1021, 'Sawangan', 'West Java'),
       (1022, 'Banyuwangi', 'East Java'),
       (1023, 'Tanjung Pinang', 'Riau'),
       (1024, 'Mumbai (Bombay)', 'Maharashtra'),
       (1025, 'Delhi', 'Delhi'),
       (1026, 'Calcutta [Kolkata]', 'West Bengali'),
       (1027, 'Chennai (Madras)', 'Tamil Nadu'),
       (1028, 'Hyderabad', 'Andhra Pradesh'),
       (1029, 'Ahmedabad', 'Gujarat'),
       (1030, 'Bangalore', 'Karnataka'),
       (1031, 'Kanpur', 'Uttar Pradesh'),
       (1032, 'Nagpur', 'Maharashtra'),
       (1033, 'Lucknow', 'Uttar Pradesh'),
       (1034, 'Pune', 'Maharashtra'),
       (1035, 'Surat', 'Gujarat'),
       (1036, 'Jaipur', 'Rajasthan'),
       (1037, 'Indore', 'Madhya Pradesh'),
       (1038, 'Bhopal', 'Madhya Pradesh'),
       (1039, 'Ludhiana', 'Punjab'),
       (1040, 'Vadodara (Baroda)', 'Gujarat'),
       (1041, 'Kalyan', 'Maharashtra'),
       (1042, 'Madurai', 'Tamil Nadu'),
       (1043, 'Haora (Howrah)', 'West Bengali'),
       (1044, 'Varanasi (Benares)', 'Uttar Pradesh'),
       (1045, 'Patna', 'Bihar'),
       (1046, 'Srinagar', 'Jammu and Kashmir'),
       (1047, 'Agra', 'Uttar Pradesh'),
       (1048, 'Coimbatore', 'Tamil Nadu'),
       (1049, 'Thane (Thana)', 'Maharashtra'),
       (1050, 'Allahabad', 'Uttar Pradesh'),
       (1051, 'Meerut', 'Uttar Pradesh'),
       (1052, 'Vishakhapatnam', 'Andhra Pradesh'),
       (1053, 'Jabalpur', 'Madhya Pradesh'),
       (1054, 'Amritsar', 'Punjab'),
       (1055, 'Faridabad', 'Haryana'),
       (1056, 'Vijayawada', 'Andhra Pradesh'),
       (1057, 'Gwalior', 'Madhya Pradesh'),
       (1058, 'Jodhpur', 'Rajasthan'),
       (1059, 'Nashik (Nasik)', 'Maharashtra'),
       (1060, 'Hubli-Dharwad', 'Karnataka'),
       (1061, 'Solapur (Sholapur)', 'Maharashtra'),
       (1062, 'Ranchi', 'Jharkhand'),
       (1063, 'Bareilly', 'Uttar Pradesh'),
       (1064, 'Guwahati (Gauhati)', 'Assam'),
       (1065, 'Shambajinagar (Aurangabad)', 'Maharashtra'),
       (1066, 'Cochin (Kochi)', 'Kerala'),
       (1067, 'Rajkot', 'Gujarat'),
       (1068, 'Kota', 'Rajasthan'),
       (1069, 'Thiruvananthapuram (Trivandrum', 'Kerala'),
       (1070, 'Pimpri-Chinchwad', 'Maharashtra'),
       (1071, 'Jalandhar (Jullundur)', 'Punjab'),
       (1072, 'Gorakhpur', 'Uttar Pradesh'),
       (1073, 'Chandigarh', 'Chandigarh'),
       (1074, 'Mysore', 'Karnataka'),
       (1075, 'Aligarh', 'Uttar Pradesh'),
       (1076, 'Guntur', 'Andhra Pradesh'),
       (1077, 'Jamshedpur', 'Jharkhand'),
       (1078, 'Ghaziabad', 'Uttar Pradesh'),
       (1079, 'Warangal', 'Andhra Pradesh'),
       (1080, 'Raipur', 'Chhatisgarh'),
       (1081, 'Moradabad', 'Uttar Pradesh'),
       (1082, 'Durgapur', 'West Bengali'),
       (1083, 'Amravati', 'Maharashtra'),
       (1084, 'Calicut (Kozhikode)', 'Kerala'),
       (1085, 'Bikaner', 'Rajasthan'),
       (1086, 'Bhubaneswar', 'Orissa'),
       (1087, 'Kolhapur', 'Maharashtra'),
       (1088, 'Kataka (Cuttack)', 'Orissa'),
       (1089, 'Ajmer', 'Rajasthan'),
       (1090, 'Bhavnagar', 'Gujarat'),
       (1091, 'Tiruchirapalli', 'Tamil Nadu'),
       (1092, 'Bhilai', 'Chhatisgarh'),
       (1093, 'Bhiwandi', 'Maharashtra'),
       (1094, 'Saharanpur', 'Uttar Pradesh'),
       (1095, 'Ulhasnagar', 'Maharashtra'),
       (1096, 'Salem', 'Tamil Nadu'),
       (1097, 'Ujjain', 'Madhya Pradesh'),
       (1098, 'Malegaon', 'Maharashtra'),
       (1099, 'Jamnagar', 'Gujarat'),
       (1100, 'Bokaro Steel City', 'Jharkhand'),
       (1101, 'Akola', 'Maharashtra'),
       (1102, 'Belgaum', 'Karnataka'),
       (1103, 'Rajahmundry', 'Andhra Pradesh'),
       (1104, 'Nellore', 'Andhra Pradesh'),
       (1105, 'Udaipur', 'Rajasthan'),
       (1106, 'New Bombay', 'Maharashtra'),
       (1107, 'Bhatpara', 'West Bengali'),
       (1108, 'Gulbarga', 'Karnataka'),
       (1109, 'New Delhi', 'Delhi'),
       (1110, 'Jhansi', 'Uttar Pradesh'),
       (1111, 'Gaya', 'Bihar'),
       (1112, 'Kakinada', 'Andhra Pradesh'),
       (1113, 'Dhule (Dhulia)', 'Maharashtra'),
       (1114, 'Panihati', 'West Bengali'),
       (1115, 'Nanded (Nander)', 'Maharashtra'),
       (1116, 'Mangalore', 'Karnataka'),
       (1117, 'Dehra Dun', 'Uttaranchal'),
       (1118, 'Kamarhati', 'West Bengali'),
       (1119, 'Davangere', 'Karnataka'),
       (1120, 'Asansol', 'West Bengali'),
       (1121, 'Bhagalpur', 'Bihar'),
       (1122, 'Bellary', 'Karnataka'),
       (1123, 'Barddhaman (Burdwan)', 'West Bengali'),
       (1124, 'Rampur', 'Uttar Pradesh'),
       (1125, 'Jalgaon', 'Maharashtra'),
       (1126, 'Muzaffarpur', 'Bihar'),
       (1127, 'Nizamabad', 'Andhra Pradesh'),
       (1128, 'Muzaffarnagar', 'Uttar Pradesh'),
       (1129, 'Patiala', 'Punjab'),
       (1130, 'Shahjahanpur', 'Uttar Pradesh'),
       (1131, 'Kurnool', 'Andhra Pradesh'),
       (1132, 'Tiruppur (Tirupper)', 'Tamil Nadu'),
       (1133, 'Rohtak', 'Haryana'),
       (1134, 'South Dum Dum', 'West Bengali'),
       (1135, 'Mathura', 'Uttar Pradesh'),
       (1136, 'Chandrapur', 'Maharashtra'),
       (1137, 'Barahanagar (Baranagar)', 'West Bengali'),
       (1138, 'Darbhanga', 'Bihar'),
       (1139, 'Siliguri (Shiliguri)', 'West Bengali'),
       (1140, 'Raurkela', 'Orissa'),
       (1141, 'Ambattur', 'Tamil Nadu'),
       (1142, 'Panipat', 'Haryana'),
       (1143, 'Firozabad', 'Uttar Pradesh'),
       (1144, 'Ichalkaranji', 'Maharashtra'),
       (1145, 'Jammu', 'Jammu and Kashmir'),
       (1146, 'Ramagundam', 'Andhra Pradesh'),
       (1147, 'Eluru', 'Andhra Pradesh'),
       (1148, 'Brahmapur', 'Orissa'),
       (1149, 'Alwar', 'Rajasthan'),
       (1150, 'Pondicherry', 'Pondicherry'),
       (1151, 'Thanjavur', 'Tamil Nadu'),
       (1152, 'Bihar Sharif', 'Bihar'),
       (1153, 'Tuticorin', 'Tamil Nadu'),
       (1154, 'Imphal', 'Manipur'),
       (1155, 'Latur', 'Maharashtra'),
       (1156, 'Sagar', 'Madhya Pradesh'),
       (1157, 'Farrukhabad-cum-Fatehgarh', 'Uttar Pradesh'),
       (1158, 'Sangli', 'Maharashtra'),
       (1159, 'Parbhani', 'Maharashtra'),
       (1160, 'Nagar Coil', 'Tamil Nadu'),
       (1161, 'Bijapur', 'Karnataka'),
       (1162, 'Kukatpalle', 'Andhra Pradesh'),
       (1163, 'Bally', 'West Bengali'),
       (1164, 'Bhilwara', 'Rajasthan'),
       (1165, 'Ratlam', 'Madhya Pradesh'),
       (1166, 'Avadi', 'Tamil Nadu'),
       (1167, 'Dindigul', 'Tamil Nadu'),
       (1168, 'Ahmadnagar', 'Maharashtra'),
       (1169, 'Bilaspur', 'Chhatisgarh'),
       (1170, 'Shimoga', 'Karnataka'),
       (1171, 'Kharagpur', 'West Bengali'),
       (1172, 'Mira Bhayandar', 'Maharashtra'),
       (1173, 'Vellore', 'Tamil Nadu'),
       (1174, 'Jalna', 'Maharashtra'),
       (1175, 'Burnpur', 'West Bengali'),
       (1176, 'Anantapur', 'Andhra Pradesh'),
       (1177, 'Allappuzha (Alleppey)', 'Kerala'),
       (1178, 'Tirupati', 'Andhra Pradesh'),
       (1179, 'Karnal', 'Haryana'),
       (1180, 'Burhanpur', 'Madhya Pradesh'),
       (1181, 'Hisar (Hissar)', 'Haryana'),
       (1182, 'Tiruvottiyur', 'Tamil Nadu'),
       (1183, 'Mirzapur-cum-Vindhyachal', 'Uttar Pradesh'),
       (1184, 'Secunderabad', 'Andhra Pradesh'),
       (1185, 'Nadiad', 'Gujarat'),
       (1186, 'Dewas', 'Madhya Pradesh'),
       (1187, 'Murwara (Katni)', 'Madhya Pradesh'),
       (1188, 'Ganganagar', 'Rajasthan'),
       (1189, 'Vizianagaram', 'Andhra Pradesh'),
       (1190, 'Erode', 'Tamil Nadu'),
       (1191, 'Machilipatnam (Masulipatam)', 'Andhra Pradesh'),
       (1192, 'Bhatinda (Bathinda)', 'Punjab'),
       (1193, 'Raichur', 'Karnataka'),
       (1194, 'Agartala', 'Tripura'),
       (1195, 'Arrah (Ara)', 'Bihar'),
       (1196, 'Satna', 'Madhya Pradesh'),
       (1197, 'Lalbahadur Nagar', 'Andhra Pradesh'),
       (1198, 'Aizawl', 'Mizoram'),
       (1199, 'Uluberia', 'West Bengali'),
       (1200, 'Katihar', 'Bihar'),
       (1201, 'Cuddalore', 'Tamil Nadu'),
       (1202, 'Hugli-Chinsurah', 'West Bengali'),
       (1203, 'Dhanbad', 'Jharkhand'),
       (1204, 'Raiganj', 'West Bengali'),
       (1205, 'Sambhal', 'Uttar Pradesh'),
       (1206, 'Durg', 'Chhatisgarh'),
       (1207, 'Munger (Monghyr)', 'Bihar'),
       (1208, 'Kanchipuram', 'Tamil Nadu'),
       (1209, 'North Dum Dum', 'West Bengali'),
       (1210, 'Karimnagar', 'Andhra Pradesh'),
       (1211, 'Bharatpur', 'Rajasthan'),
       (1212, 'Sikar', 'Rajasthan'),
       (1213, 'Hardwar (Haridwar)', 'Uttaranchal'),
       (1214, 'Dabgram', 'West Bengali'),
       (1215, 'Morena', 'Madhya Pradesh'),
       (1216, 'Noida', 'Uttar Pradesh'),
       (1217, 'Hapur', 'Uttar Pradesh'),
       (1218, 'Bhusawal', 'Maharashtra'),
       (1219, 'Khandwa', 'Madhya Pradesh'),
       (1220, 'Yamuna Nagar', 'Haryana'),
       (1221, 'Sonipat (Sonepat)', 'Haryana'),
       (1222, 'Tenali', 'Andhra Pradesh'),
       (1223, 'Raurkela Civil Township', 'Orissa'),
       (1224, 'Kollam (Quilon)', 'Kerala'),
       (1225, 'Kumbakonam', 'Tamil Nadu'),
       (1226, 'Ingraj Bazar (English Bazar)', 'West Bengali'),
       (1227, 'Timkur', 'Karnataka'),
       (1228, 'Amroha', 'Uttar Pradesh'),
       (1229, 'Serampore', 'West Bengali'),
       (1230, 'Chapra', 'Bihar'),
       (1231, 'Pali', 'Rajasthan'),
       (1232, 'Maunath Bhanjan', 'Uttar Pradesh'),
       (1233, 'Adoni', 'Andhra Pradesh'),
       (1234, 'Jaunpur', 'Uttar Pradesh'),
       (1235, 'Tirunelveli', 'Tamil Nadu'),
       (1236, 'Bahraich', 'Uttar Pradesh'),
       (1237, 'Gadag Betigeri', 'Karnataka'),
       (1238, 'Proddatur', 'Andhra Pradesh'),
       (1239, 'Chittoor', 'Andhra Pradesh'),
       (1240, 'Barrackpur', 'West Bengali'),
       (1241, 'Bharuch (Broach)', 'Gujarat'),
       (1242, 'Naihati', 'West Bengali'),
       (1243, 'Shillong', 'Meghalaya'),
       (1244, 'Sambalpur', 'Orissa'),
       (1245, 'Junagadh', 'Gujarat'),
       (1246, 'Rae Bareli', 'Uttar Pradesh'),
       (1247, 'Rewa', 'Madhya Pradesh'),
       (1248, 'Gurgaon', 'Haryana'),
       (1249, 'Khammam', 'Andhra Pradesh'),
       (1250, 'Bulandshahr', 'Uttar Pradesh'),
       (1251, 'Navsari', 'Gujarat'),
       (1252, 'Malkajgiri', 'Andhra Pradesh'),
       (1253, 'Midnapore (Medinipur)', 'West Bengali'),
       (1254, 'Miraj', 'Maharashtra'),
       (1255, 'Raj Nandgaon', 'Chhatisgarh'),
       (1256, 'Alandur', 'Tamil Nadu'),
       (1257, 'Puri', 'Orissa'),
       (1258, 'Navadwip', 'West Bengali'),
       (1259, 'Sirsa', 'Haryana'),
       (1260, 'Korba', 'Chhatisgarh'),
       (1261, 'Faizabad', 'Uttar Pradesh'),
       (1262, 'Etawah', 'Uttar Pradesh'),
       (1263, 'Pathankot', 'Punjab'),
       (1264, 'Gandhinagar', 'Gujarat'),
       (1265, 'Palghat (Palakkad)', 'Kerala'),
       (1266, 'Veraval', 'Gujarat'),
       (1267, 'Hoshiarpur', 'Punjab'),
       (1268, 'Ambala', 'Haryana'),
       (1269, 'Sitapur', 'Uttar Pradesh'),
       (1270, 'Bhiwani', 'Haryana'),
       (1271, 'Cuddapah', 'Andhra Pradesh'),
       (1272, 'Bhimavaram', 'Andhra Pradesh'),
       (1273, 'Krishnanagar', 'West Bengali'),
       (1274, 'Chandannagar', 'West Bengali'),
       (1275, 'Mandya', 'Karnataka'),
       (1276, 'Dibrugarh', 'Assam'),
       (1277, 'Nandyal', 'Andhra Pradesh'),
       (1278, 'Balurghat', 'West Bengali'),
       (1279, 'Neyveli', 'Tamil Nadu'),
       (1280, 'Fatehpur', 'Uttar Pradesh'),
       (1281, 'Mahbubnagar', 'Andhra Pradesh'),
       (1282, 'Budaun', 'Uttar Pradesh'),
       (1283, 'Porbandar', 'Gujarat'),
       (1284, 'Silchar', 'Assam'),
       (1285, 'Berhampore (Baharampur)', 'West Bengali'),
       (1286, 'Purnea (Purnia)', 'Jharkhand'),
       (1287, 'Bankura', 'West Bengali'),
       (1288, 'Rajapalaiyam', 'Tamil Nadu'),
       (1289, 'Titagarh', 'West Bengali'),
       (1290, 'Halisahar', 'West Bengali'),
       (1291, 'Hathras', 'Uttar Pradesh'),
       (1292, 'Bhir (Bid)', 'Maharashtra'),
       (1293, 'Pallavaram', 'Tamil Nadu'),
       (1294, 'Anand', 'Gujarat'),
       (1295, 'Mango', 'Jharkhand'),
       (1296, 'Santipur', 'West Bengali'),
       (1297, 'Bhind', 'Madhya Pradesh'),
       (1298, 'Gondiya', 'Maharashtra'),
       (1299, 'Tiruvannamalai', 'Tamil Nadu'),
       (1300, 'Yeotmal (Yavatmal)', 'Maharashtra'),
       (1301, 'Kulti-Barakar', 'West Bengali'),
       (1302, 'Moga', 'Punjab'),
       (1303, 'Shivapuri', 'Madhya Pradesh'),
       (1304, 'Bidar', 'Karnataka'),
       (1305, 'Guntakal', 'Andhra Pradesh'),
       (1306, 'Unnao', 'Uttar Pradesh'),
       (1307, 'Barasat', 'West Bengali'),
       (1308, 'Tambaram', 'Tamil Nadu'),
       (1309, 'Abohar', 'Punjab'),
       (1310, 'Pilibhit', 'Uttar Pradesh'),
       (1311, 'Valparai', 'Tamil Nadu'),
       (1312, 'Gonda', 'Uttar Pradesh'),
       (1313, 'Surendranagar', 'Gujarat'),
       (1314, 'Qutubullapur', 'Andhra Pradesh'),
       (1315, 'Beawar', 'Rajasthan'),
       (1316, 'Hindupur', 'Andhra Pradesh'),
       (1317, 'Gandhidham', 'Gujarat'),
       (1318, 'Haldwani-cum-Kathgodam', 'Uttaranchal'),
       (1319, 'Tellicherry (Thalassery)', 'Kerala'),
       (1320, 'Wardha', 'Maharashtra'),
       (1321, 'Rishra', 'West Bengali'),
       (1322, 'Bhuj', 'Gujarat'),
       (1323, 'Modinagar', 'Uttar Pradesh'),
       (1324, 'Gudivada', 'Andhra Pradesh'),
       (1325, 'Basirhat', 'West Bengali'),
       (1326, 'Uttarpara-Kotrung', 'West Bengali'),
       (1327, 'Ongole', 'Andhra Pradesh'),
       (1328, 'North Barrackpur', 'West Bengali'),
       (1329, 'Guna', 'Madhya Pradesh'),
       (1330, 'Haldia', 'West Bengali'),
       (1331, 'Habra', 'West Bengali'),
       (1332, 'Kanchrapara', 'West Bengali'),
       (1333, 'Tonk', 'Rajasthan'),
       (1334, 'Champdani', 'West Bengali'),
       (1335, 'Orai', 'Uttar Pradesh'),
       (1336, 'Pudukkottai', 'Tamil Nadu'),
       (1337, 'Sasaram', 'Bihar'),
       (1338, 'Hazaribag', 'Jharkhand'),
       (1339, 'Palayankottai', 'Tamil Nadu'),
       (1340, 'Banda', 'Uttar Pradesh'),
       (1341, 'Godhra', 'Gujarat'),
       (1342, 'Hospet', 'Karnataka'),
       (1343, 'Ashoknagar-Kalyangarh', 'West Bengali'),
       (1344, 'Achalpur', 'Maharashtra'),
       (1345, 'Patan', 'Gujarat'),
       (1346, 'Mandasor', 'Madhya Pradesh'),
       (1347, 'Damoh', 'Madhya Pradesh'),
       (1348, 'Satara', 'Maharashtra'),
       (1349, 'Meerut Cantonment', 'Uttar Pradesh'),
       (1350, 'Dehri', 'Bihar'),
       (1351, 'Delhi Cantonment', 'Delhi'),
       (1352, 'Chhindwara', 'Madhya Pradesh'),
       (1353, 'Bansberia', 'West Bengali'),
       (1354, 'Nagaon', 'Assam'),
       (1355, 'Kanpur Cantonment', 'Uttar Pradesh'),
       (1356, 'Vidisha', 'Madhya Pradesh'),
       (1357, 'Bettiah', 'Bihar'),
       (1358, 'Purulia', 'Jharkhand'),
       (1359, 'Hassan', 'Karnataka'),
       (1360, 'Ambala Sadar', 'Haryana'),
       (1361, 'Baidyabati', 'West Bengali'),
       (1362, 'Morvi', 'Gujarat'),
       (1363, 'Raigarh', 'Chhatisgarh'),
       (1364, 'Vejalpur', 'Gujarat'),
       (1365, 'Baghdad', 'Baghdad'),
       (1366, 'Mosul', 'Ninawa'),
       (1367, 'Irbil', 'Irbil'),
       (1368, 'Kirkuk', 'al-Tamim'),
       (1369, 'Basra', 'Basra'),
       (1370, 'al-Sulaymaniya', 'al-Sulaymaniya'),
       (1371, 'al-Najaf', 'al-Najaf'),
       (1372, 'Karbala', 'Karbala'),
       (1373, 'al-Hilla', 'Babil'),
       (1374, 'al-Nasiriya', 'DhiQar'),
       (1375, 'al-Amara', 'Maysan'),
       (1376, 'al-Diwaniya', 'al-Qadisiya'),
       (1377, 'al-Ramadi', 'al-Anbar'),
       (1378, 'al-Kut', 'Wasit'),
       (1379, 'Baquba', 'Diyala'),
       (1380, 'Teheran', 'Teheran'),
       (1381, 'Mashhad', 'Khorasan'),
       (1382, 'Esfahan', 'Esfahan'),
       (1383, 'Tabriz', 'East Azerbaidzan'),
       (1384, 'Shiraz', 'Fars'),
       (1385, 'Karaj', 'Teheran'),
       (1386, 'Ahvaz', 'Khuzestan'),
       (1387, 'Qom', 'Qom'),
       (1388, 'Kermanshah', 'Kermanshah'),
       (1389, 'Urmia', 'West Azerbaidzan'),
       (1390, 'Zahedan', 'Sistan va Baluchesta'),
       (1391, 'Rasht', 'Gilan'),
       (1392, 'Hamadan', 'Hamadan'),
       (1393, 'Kerman', 'Kerman'),
       (1394, 'Arak', 'Markazi'),
       (1395, 'Ardebil', 'Ardebil'),
       (1396, 'Yazd', 'Yazd'),
       (1397, 'Qazvin', 'Qazvin'),
       (1398, 'Zanjan', 'Zanjan'),
       (1399, 'Sanandaj', 'Kordestan'),
       (1400, 'Bandar-e-Abbas', 'Hormozgan'),
       (1401, 'Khorramabad', 'Lorestan'),
       (1402, 'Eslamshahr', 'Teheran'),
       (1403, 'Borujerd', 'Lorestan'),
       (1404, 'Abadan', 'Khuzestan'),
       (1405, 'Dezful', 'Khuzestan'),
       (1406, 'Kashan', 'Esfahan'),
       (1407, 'Sari', 'Mazandaran'),
       (1408, 'Gorgan', 'Golestan'),
       (1409, 'Najafabad', 'Esfahan'),
       (1410, 'Sabzevar', 'Khorasan'),
       (1411, 'Khomeynishahr', 'Esfahan'),
       (1412, 'Amol', 'Mazandaran'),
       (1413, 'Neyshabur', 'Khorasan'),
       (1414, 'Babol', 'Mazandaran'),
       (1415, 'Khoy', 'West Azerbaidzan'),
       (1416, 'Malayer', 'Hamadan'),
       (1417, 'Bushehr', 'Bushehr'),
       (1418, 'Qaemshahr', 'Mazandaran'),
       (1419, 'Qarchak', 'Teheran'),
       (1420, 'Qods', 'Teheran'),
       (1421, 'Sirjan', 'Kerman'),
       (1422, 'Bojnurd', 'Khorasan'),
       (1423, 'Maragheh', 'East Azerbaidzan'),
       (1424, 'Birjand', 'Khorasan'),
       (1425, 'Ilam', 'Ilam'),
       (1426, 'Bukan', 'West Azerbaidzan'),
       (1427, 'Masjed-e-Soleyman', 'Khuzestan'),
       (1428, 'Saqqez', 'Kordestan'),
       (1429, 'Gonbad-e Qabus', 'Mazandaran'),
       (1430, 'Saveh', 'Qom'),
       (1431, 'Mahabad', 'West Azerbaidzan'),
       (1432, 'Varamin', 'Teheran'),
       (1433, 'Andimeshk', 'Khuzestan'),
       (1434, 'Khorramshahr', 'Khuzestan'),
       (1435, 'Shahrud', 'Semnan'),
       (1436, 'Marv Dasht', 'Fars'),
       (1437, 'Zabol', 'Sistan va Baluchesta'),
       (1438, 'Shahr-e Kord', 'Chaharmahal va Bakht'),
       (1439, 'Bandar-e Anzali', 'Gilan'),
       (1440, 'Rafsanjan', 'Kerman'),
       (1441, 'Marand', 'East Azerbaidzan'),
       (1442, 'Torbat-e Heydariyeh', 'Khorasan'),
       (1443, 'Jahrom', 'Fars'),
       (1444, 'Semnan', 'Semnan'),
       (1445, 'Miandoab', 'West Azerbaidzan'),
       (1446, 'Qomsheh', 'Esfahan'),
       (1447, 'Dublin', 'Leinster'),
       (1448, 'Cork', 'Munster'),
       (1449, 'Reykjav', 'H?fu?borgarsv?'),
       (1450, 'Jerusalem', 'Jerusalem'),
       (1451, 'Tel Aviv-Jaffa', 'Tel Aviv'),
       (1452, 'Haifa', 'Haifa'),
       (1453, 'Rishon Le Ziyyon', 'Ha Merkaz'),
       (1454, 'Beerseba', 'Ha Darom'),
       (1455, 'Holon', 'Tel Aviv'),
       (1456, 'Petah Tiqwa', 'Ha Merkaz'),
       (1457, 'Ashdod', 'Ha Darom'),
       (1458, 'Netanya', 'Ha Merkaz'),
       (1459, 'Bat Yam', 'Tel Aviv'),
       (1460, 'Bene Beraq', 'Tel Aviv'),
       (1461, 'Ramat Gan', 'Tel Aviv'),
       (1462, 'Ashqelon', 'Ha Darom'),
       (1463, 'Rehovot', 'Ha Merkaz'),
       (1464, 'Roma', 'Latium'),
       (1465, 'Milano', 'Lombardia'),
       (1466, 'Napoli', 'Campania'),
       (1467, 'Torino', 'Piemonte'),
       (1468, 'Palermo', 'Sisilia'),
       (1469, 'Genova', 'Liguria'),
       (1470, 'Bologna', 'Emilia-Romagna'),
       (1471, 'Firenze', 'Toscana'),
       (1472, 'Catania', 'Sisilia'),
       (1473, 'Bari', 'Apulia'),
       (1474, 'Venezia', 'Veneto'),
       (1475, 'Messina', 'Sisilia'),
       (1476, 'Verona', 'Veneto'),
       (1477, 'Trieste', 'Friuli-Venezia Giuli'),
       (1478, 'Padova', 'Veneto'),
       (1479, 'Taranto', 'Apulia'),
       (1480, 'Brescia', 'Lombardia'),
       (1481, 'Reggio di Calabria', 'Calabria'),
       (1482, 'Modena', 'Emilia-Romagna'),
       (1483, 'Prato', 'Toscana'),
       (1484, 'Parma', 'Emilia-Romagna'),
       (1485, 'Cagliari', 'Sardinia'),
       (1486, 'Livorno', 'Toscana'),
       (1487, 'Perugia', 'Umbria'),
       (1488, 'Foggia', 'Apulia'),
       (1489, 'Reggio nell? Emilia', 'Emilia-Romagna'),
       (1490, 'Salerno', 'Campania'),
       (1491, 'Ravenna', 'Emilia-Romagna'),
       (1492, 'Ferrara', 'Emilia-Romagna'),
       (1493, 'Rimini', 'Emilia-Romagna'),
       (1494, 'Syrakusa', 'Sisilia'),
       (1495, 'Sassari', 'Sardinia'),
       (1496, 'Monza', 'Lombardia'),
       (1497, 'Bergamo', 'Lombardia'),
       (1498, 'Pescara', 'Abruzzit'),
       (1499, 'Latina', 'Latium'),
       (1500, 'Vicenza', 'Veneto'),
       (1501, 'Terni', 'Umbria'),
       (1502, 'Forl', 'Emilia-Romagna'),
       (1503, 'Trento', 'Trentino-Alto Adige'),
       (1504, 'Novara', 'Piemonte'),
       (1505, 'Piacenza', 'Emilia-Romagna'),
       (1506, 'Ancona', 'Marche'),
       (1507, 'Lecce', 'Apulia'),
       (1508, 'Bolzano', 'Trentino-Alto Adige'),
       (1509, 'Catanzaro', 'Calabria'),
       (1510, 'La Spezia', 'Liguria'),
       (1511, 'Udine', 'Friuli-Venezia Giuli'),
       (1512, 'Torre del Greco', 'Campania'),
       (1513, 'Andria', 'Apulia'),
       (1514, 'Brindisi', 'Apulia'),
       (1515, 'Giugliano in Campania', 'Campania'),
       (1516, 'Pisa', 'Toscana'),
       (1517, 'Barletta', 'Apulia'),
       (1518, 'Arezzo', 'Toscana'),
       (1519, 'Alessandria', 'Piemonte'),
       (1520, 'Cesena', 'Emilia-Romagna'),
       (1521, 'Pesaro', 'Marche'),
       (1522, 'Dili', 'Dili'),
       (1523, 'Wien', 'Wien'),
       (1524, 'Graz', 'Steiermark'),
       (1525, 'Linz', 'North Austria'),
       (1526, 'Salzburg', 'Salzburg'),
       (1527, 'Innsbruck', 'Tiroli'),
       (1528, 'Klagenfurt', 'K?rnten'),
       (1529, 'Spanish Town', 'St. Catherine'),
       (1530, 'Kingston', 'St. Andrew'),
       (1531, 'Portmore', 'St. Andrew'),
       (1532, 'Tokyo', 'Tokyo-to'),
       (1533, 'Jokohama [Yokohama]', 'Kanagawa'),
       (1534, 'Osaka', 'Osaka'),
       (1535, 'Nagoya', 'Aichi'),
       (1536, 'Sapporo', 'Hokkaido'),
       (1537, 'Kioto', 'Kyoto'),
       (1538, 'Kobe', 'Hyogo'),
       (1539, 'Fukuoka', 'Fukuoka'),
       (1540, 'Kawasaki', 'Kanagawa'),
       (1541, 'Hiroshima', 'Hiroshima'),
       (1542, 'Kitakyushu', 'Fukuoka'),
       (1543, 'Sendai', 'Miyagi'),
       (1544, 'Chiba', 'Chiba'),
       (1545, 'Sakai', 'Osaka'),
       (1546, 'Kumamoto', 'Kumamoto'),
       (1547, 'Okayama', 'Okayama'),
       (1548, 'Sagamihara', 'Kanagawa'),
       (1549, 'Hamamatsu', 'Shizuoka'),
       (1550, 'Kagoshima', 'Kagoshima'),
       (1551, 'Funabashi', 'Chiba'),
       (1552, 'Higashiosaka', 'Osaka'),
       (1553, 'Hachioji', 'Tokyo-to'),
       (1554, 'Niigata', 'Niigata'); --
UPDATE `{$wpdb->prefix}incluyeme_provincias`
SET cities_provin = 'Los Rios'
WHERE cities_provin = 'Los R?os'; --
UPDATE `{$wpdb->prefix}incluyeme_cities`
SET cities_location = 'Los Rios'
WHERE cities_location = 'Los R?os'; --


/*Panama*/
UPDATE `{$wpdb->prefix}incluyeme_provincias`
SET cities_provin = 'Panamá'
WHERE cities_provin = 'Panam'; --

UPDATE `{$wpdb->prefix}incluyeme_cities`
SET cities_location = 'Panamá'
WHERE cities_location = 'Panam'; --

UPDATE `{$wpdb->prefix}incluyeme_cities`
SET cities_name = 'Ciudad de Panamá'
WHERE cities_name = 'Ciudad de Panam'; --

DELETE
from `{$wpdb->prefix}incluyeme_provincias`
WHERE country_code = 'PA'
  AND cities_provin IN ('Baluchistan', 'Islamabad', 'Nothwest Border Prov', 'Punjab', 'Sind', 'Sindh'); --

INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Colón',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Chiriquí',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Veraguas',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Bocas del Toro',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Coclé',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Herrera',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Panamá Oeste',
    country_code  = 'PA'; --
INSERT INTO `{$wpdb->prefix}incluyeme_provincias`
set cities_provin = 'Los Santos',
    country_code  = 'PA'; --

INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Colón', cities_location =  'Colón'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'David', cities_location =  'Chiriquí'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'La Chorrera', cities_location =  'Panamá Oeste'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Santiago', cities_location =  'Veraguas'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Changuinola', cities_location =  'Bocas del Toro'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Penonomé', cities_location =  'Coclé'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Bugaba', cities_location =  'Chiriquí'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Puerto Armuelles', cities_location =  'Chiriquí'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Antón', cities_location =  'Coclé'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Chepo', cities_location =  'Panamá'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Chitré', cities_location =  'Herrera'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Aguadulce', cities_location =  'Coclé'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Capira', cities_location =  'Panamá Oeste'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Chame', cities_location =  'Panamá Oeste'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Soná', cities_location =  'Veraguas'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Almirante', cities_location =  'Bocas del Toro'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'La Pintada', cities_location =  'Coclé'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'Las Tablas', cities_location =  'Los Santos'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'La Villa de Los Santos', cities_location =  'Los Santos'; --
INSERT INTO `{$wpdb->prefix}incluyeme_cities` set cities_name = 'La Villa de Los Santos', cities_location =  'Los Santos'; --

DELETE t1 FROM `{$wpdb->prefix}incluyeme_cities` t1
	               INNER JOIN `{$wpdb->prefix}incluyeme_cities` t2
WHERE t1.incluyeme_cities_id > t2.incluyeme_cities_id AND t1.cities_name = t2.cities_name; --

DELETE t1 FROM `{$wpdb->prefix}incluyeme_provincias` t1
	               INNER JOIN `{$wpdb->prefix}incluyeme_provincias` t2
WHERE t1.incluyeme_provincias_id > t2.incluyeme_provincias_id AND t1.cities_provin = t2.cities_provin; --
